[app]
listen_port=8000
listen_host=0.0.0.0
log_level=INFO
logs_rotation=7

; Used only to display commands lines in UI
restic_executable_path=restic

; The default path to restore things
backup_mountpoint=/backup

; Command to append at the end of the mount command.
;mount_command_append=; umount /backup

; Time after a new snapshot list analysis will be performed (hours)
snapshots_list_cache_file_retention=18

; How many hours to keep snapshots cache file
snapshot_cache_file_retention=96

; You can hide the content of those paths to reduce bandwidth usage
; Useful when the directory is the "restore all or nothing" king
ignore_path = /userdata/usr/src
              /userdata/.*/venv

; You can have multiple repos, they must start with [repo:]
[repo:repo1]
; cannot be empty
url=url_to_my_repo
; cannot be empty
password=MySuperP@ssw0rd
; You can ignore paths for specific repo
ignore_path = /userdata/snap

[repo:repo2]
url=url_to_my_repo_but_another_one
password=another_password

; you can add any parameter you want, they will not be used by this app but will be sent by the api
;optional_param=optional_value